services:
  medical-rag-pipeline:
    build: .
    container_name: medical-rag-pipeline
    volumes:
      - ./docs:/docs
      - ./app/output:/app/output
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia 