services:
  medical-doc-test:
    build: .
    container_name: medical-doc-test
    volumes:
      - ./data:/app/data
      - ./app/output:/app/output
      - ./test_*.py:/app/test_*.py
      - ./docs:/app/docs
    environment:
      - PYTHONPATH=/app
    command: ["python", "-m", "pytest", "test_*.py", "-v"]
    profiles:
      - test

  medical-doc-interactive:
    build: .
    container_name: medical-doc-interactive
    volumes:
      - ./data:/app/data
      - ./app/output:/app/output
      - ./test_*.py:/app/test_*.py
      - ./docs:/app/docs
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true
    profiles:
      - interactive 